"""Load and parse external check results from CSV files.

Integrates external (admin, manual, or third-party) check results into the audit
by converting them to CheckResult objects that can be merged with automated
check results. Supports hybrid validation: strict on format/score/status, warns
on Ref/Pillar/Workspace mismatches.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from ..core.enums import Pillar, Severity, Status, Layer, Scope
from ..core.models import CheckResult


class ExternalCheckError(RuntimeError):
    """Fatal error loading external checks — audit cannot proceed."""


def _parse_pillar(pillar_str: str) -> Pillar:
    """Extract pillar enum from CSV text like '06 Security & Access Control (12%)'.
    
    Maps to the closest Pillar enum member. If no match, raises ExternalCheckError.
    """
    if not pillar_str:
        raise ExternalCheckError("Pillar column is empty")
    
    # Extract pillar name (remove number prefix and percentage suffix)
    # e.g., "06 Security & Access Control (12%)" -> "Security & Access Control"
    text = pillar_str.strip()
    
    # Try direct match against Pillar enum
    for pillar in Pillar:
        if pillar.value.lower() in text.lower():
            return pillar
    
    # Fallback: check common mappings
    mappings = {
        "security": Pillar.SECURITY,
        "governance": Pillar.GOVERNANCE,
        "operations": Pillar.OPERATIONS,
        "performance": Pillar.PERFORMANCE,
        "cost": Pillar.COST,
        "data quality": Pillar.GOVERNANCE,  # Sometimes grouped
        "data management": Pillar.GOVERNANCE,
    }
    
    for key, pillar in mappings.items():
        if key in text.lower():
            return pillar
    
    raise ExternalCheckError(f"Unknown pillar: '{pillar_str}'")


def _parse_status(status_str: str) -> Status:
    """Parse status string from CSV.
    
    Valid: PASS, FAIL, PARTIAL, NOT SCORED
    Maps NOT SCORED to N/A.
    """
    if not status_str:
        raise ExternalCheckError("Status column is empty")
    
    status_str = status_str.strip().upper()
    
    if status_str == "NOT SCORED":
        return Status.NA
    
    try:
        return Status(status_str)
    except ValueError:
        raise ExternalCheckError(
            f"Invalid status '{status_str}'. Must be: PASS, FAIL, PARTIAL, NOT SCORED"
        )


def _parse_score(score_str: str, status: Status) -> int | None:
    """Parse score from CSV.
    
    Valid: 0-3 or blank. A blank score means the row is unscored (N/A or INFO).
    """
    if not score_str or score_str.strip() == "":
        # Unscored statuses (N/A, INFO) legitimately have no score.
        if status in (Status.NA, Status.INFO):
            return None
        raise ExternalCheckError(
            f"Score cannot be blank for status {status.value}"
        )
    
    try:
        score = int(score_str.strip())
    except ValueError:
        raise ExternalCheckError(f"Score must be 0-3, got '{score_str}'")
    
    if score < 0 or score > 3:
        raise ExternalCheckError(f"Score must be 0-3, got {score}")
    
    # Lenient: accept any score with any status. The CSV is the source of truth.
    # (Previously we enforced FAIL=0, PASS=3, but real CSVs have partial scores.)
    
    return score


def load_external_checks(
    csv_path: str | Path,
    target_workspaces: set[str] | None = None,
) -> tuple[list[CheckResult], list[str]]:
    """Load external check results from CSV file.
    
    Accepts the CSV format generated by the audit tool export:
    Workspace, Layer role, Object, Check ID, Ref, Title, Validation, Pillar, 
    Status, Score, Severity, Source, Evidence, Recommendation
    
    Or minimal format:
    Workspace, Ref, Check ID, Status, Score, Title, Pillar
    
    Args:
        csv_path: Path to AdminChecks.csv (or similar format).
        target_workspaces: Set of workspace IDs expected in the project. If
            provided, workspaces in the CSV not in this set trigger warnings.
    
    Returns:
        (results, warnings) where:
        - results: CheckResult[] ready to merge into audit
        - warnings: List of non-fatal issues (validation mismatches)
    
    Raises:
        ExternalCheckError: On fatal errors (file not found, bad format, invalid
            score/status, missing required columns).
    """
    csv_path = Path(csv_path)
    
    if not csv_path.exists():
        raise ExternalCheckError(f"CSV file not found: {csv_path}")
    
    if not csv_path.is_file():
        raise ExternalCheckError(f"Not a file: {csv_path}")
    
    results: list[CheckResult] = []
    warnings: list[str] = []
    
    # Required columns - minimal version
    required_columns = {"Workspace", "Ref", "Check ID", "Status", "Score", "Title", "Pillar"}
    
    try:
        # utf-8-sig strips the BOM that Excel writes at the start of the file;
        # without it the first header becomes "\ufeffWorkspace" and never matches.
        with open(csv_path, encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            
            if reader.fieldnames is None:
                raise ExternalCheckError("CSV file is empty")
            
            fieldnames = {(name or "").strip() for name in reader.fieldnames}
            missing = required_columns - fieldnames
            if missing:
                raise ExternalCheckError(
                    f"CSV missing required columns: {', '.join(sorted(missing))}. "
                    f"Your CSV has: {', '.join(sorted(fieldnames))}"
                )
            
            for row_num, raw_row in enumerate(reader, start=2):  # Start at 2 (after header)
                try:
                    # Normalise header keys (strip whitespace/BOM remnants)
                    row = {
                        (k or "").strip(): (v or "")
                        for k, v in raw_row.items()
                    }
                    workspace = row.get("Workspace", "").strip()
                    ref = row.get("Ref", "").strip()
                    check_id = row.get("Check ID", "").strip()
                    title = row.get("Title", "").strip()
                    pillar_str = row.get("Pillar", "").strip()
                    status_str = row.get("Status", "").strip()
                    score_str = row.get("Score", "").strip()
                    severity_str = row.get("Severity", "Medium").strip()
                    evidence = row.get("Evidence", "").strip()
                    obj = row.get("Object", "").strip()
                    layer_str = row.get("Layer role", "").strip()
                    
                    # Validate required fields
                    if not workspace:
                        raise ExternalCheckError(f"Row {row_num}: Workspace is empty")
                    if not check_id:
                        raise ExternalCheckError(f"Row {row_num}: Check ID is empty")
                    if not ref:
                        raise ExternalCheckError(f"Row {row_num}: Ref is empty")
                    if not title:
                        raise ExternalCheckError(f"Row {row_num}: Title is empty")
                    
                    # Parse status first (needed for score validation)
                    status = _parse_status(status_str)
                    
                    # Parse score (validates against status)
                    score = _parse_score(score_str, status)
                    
                    # Parse pillar
                    try:
                        pillar = _parse_pillar(pillar_str)
                    except ExternalCheckError as e:
                        warnings.append(f"Row {row_num}: {str(e)} — skipping")
                        continue
                    
                    # Parse severity (lenient — use Medium as default)
                    try:
                        severity = Severity(severity_str) if severity_str else Severity.MEDIUM
                    except ValueError:
                        severity = Severity.MEDIUM
                        warnings.append(
                            f"Row {row_num}: Unknown severity '{severity_str}' — using MEDIUM"
                        )
                    
                    # Note: no workspace-membership warning. External checks are
                    # applied workspace-agnostically, and the CSV carries workspace
                    # *names* while project targets are GUIDs, so a comparison here
                    # would always report a mismatch.
                    
                    # Determine scored flag (N/A and INFO rows are unscored)
                    scored = status not in (Status.NA, Status.INFO) and score is not None
                    
                    # Build CheckResult
                    result = CheckResult(
                        check_id=check_id,
                        ref=ref,
                        title=title,
                        pillar=pillar,
                        status=status,
                        score=score,
                        coverage=None,
                        evidence=evidence,
                        recommendation="",  # External checks don't have remediation in CSV
                        severity=severity,
                        workspace=workspace,
                        layer=Layer.parse(layer_str) if layer_str else Layer.ANY,
                        obj=obj,
                        scope=Scope.WORKSPACE,  # External checks are workspace-scoped by default
                        weight=1.0,
                        scored=scored,
                        source="external",  # Mark as external source
                    )
                    results.append(result)
                
                except ExternalCheckError as e:
                    raise ExternalCheckError(f"Row {row_num}: {str(e)}")
        
        if not results:
            raise ExternalCheckError("CSV contains no valid check results")
    
    except csv.Error as e:
        raise ExternalCheckError(f"CSV parsing error: {e}")
    except ExternalCheckError:
        raise
    except Exception as e:
        raise ExternalCheckError(f"Unexpected error reading CSV: {e}")
    
    return results, warnings
